[program:queue-ppdb]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/pesantren-ppdb/artisan queue:work --sleep=3 --tries=3 --max-time=3600
user=www-data
autostart=true
autorestart=true
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/queue-ppdb.log
stopasgroup=true
killasgroup=true
